version: '3'

volumes:
  pihole-logs:

services:
  kafkaconnect:
    container_name: kafkaconnect
    # For x86 arch systems
    image: quay.io/evanshortiss/kafka-connect-simple:latest
    # For arm arch systems
    # image: quay.io/evanshortiss/kafka-connect-simple:latest-arm
    depends_on:
      - pihole
    volumes:
      - './kafka-config/:/usr/src/app/config/'
      - 'pihole-logs:/var/pihole-logs/'
    restart: unless-stopped
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 8080:80/tcp
    environment:
      TZ: 'Europe/Dublin'
      WEBPASSWORD: 'password'
      DNS1: '1.1.1.1'
      DNS2: '1.0.0.1'
    volumes:
      - './pihole-config/etc-dnsmasq.d/:/etc/dnsmasq.d/'
      - 'pihole-logs:/var/log/'
    restart: unless-stopped
